name: deployment on kysrv

on:
  push:
    branches: [master]

jobs:
  job1:
    runs-on: self-hosted

    env:
      CI: false

    steps:
      - uses: actions/checkout@v2
      - name: Installing new potential dependencies
        run: yarn install

      - name: Building the new source code
        run: yarn run build

      - run: ls -la
      - name: Caching the new source code (for nginx)
        run: cp -r ./build/* ~/www/tomate-front

      - name: Successfully deployed :]
        run: echo "Deployment finished"
